import {
  pgTable,
  text,
  integer,
  doublePrecision,
  boolean,
  jsonb,
} from 'drizzle-orm/pg-core';
import { Order } from '../types';

export const users = pgTable('users', {
  id: text('id').primaryKey(),
  username: text('username').default('').notNull(),
  password: text('password').default('').notNull(),
  name: text('name').notNull(),
  email: text('email').default('').notNull(),
  phone: text('phone').default('').notNull(),
  role: text('role').notNull(),
  status: text('status').default('ACTIVE').notNull(),
  vendorId: text('vendor_id'),
  city: text('city'),
  address: text('address'),
  lat: doublePrecision('lat'),
  lng: doublePrecision('lng'),
  createdAt: text('created_at').notNull(),
});

export const vendors = pgTable('vendors', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  ownerId: text('owner_id').default('').notNull(),
  ownerName: text('owner_name').notNull(),
  phone: text('phone').notNull(),
  bio: text('bio').default('').notNull(),
  category: text('category').default('').notNull(),
  addressText: text('address_text').default('').notNull(),
  locationLat: doublePrecision('location_lat').default(24.7136).notNull(),
  locationLng: doublePrecision('location_lng').default(46.6753).notNull(),
  maroofNumber: text('maroof_number'),
  status: text('status').notNull(),
  rejectionReason: text('rejection_reason'),
  rating: doublePrecision('rating').notNull(),
  joinedAt: text('joined_at').default('').notNull(),
  avatar: text('avatar').default('').notNull(),
  coverImage: text('cover_image').default('').notNull(),
  deliveryFee: doublePrecision('delivery_fee'),
  commissionRate: doublePrecision('commission_rate'),
  nationalIdOrCR: text('national_id_or_cr').default('').notNull(),
  city: text('city').default('').notNull(),
  address: text('address'),
  lat: doublePrecision('lat'),
  lng: doublePrecision('lng'),
  categoryIds: jsonb('category_ids').$type<string[]>().default([]).notNull(),
  description: text('description').default('').notNull(),
  logo: text('logo').default('').notNull(),
  banner: text('banner').default('').notNull(),
  suspensionReason: text('suspension_reason'),
  isHidden: boolean('is_hidden'),
  hideContactDetails: boolean('hide_contact_details'),
  submittedAt: text('submitted_at').default('').notNull(),
  approvedAt: text('approved_at'),
  bankAccount: jsonb('bank_account')
    .$type<{ bankName: string; iban: string; accountHolder: string }>()
    .default({ bankName: '', iban: '', accountHolder: '' })
    .notNull(),
  totalSalesCount: integer('total_sales_count').default(0).notNull(),
});

export const categories = pgTable('categories', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  icon: text('icon').notNull(),
  description: text('description').notNull(),
  sortOrder: integer('sort_order').default(0).notNull(),
});

export const products = pgTable('products', {
  id: text('id').primaryKey(),
  vendorId: text('vendor_id').notNull(),
  vendorName: text('vendor_name').notNull(),
  categoryId: text('category_id').notNull(),
  name: text('name').notNull(),
  description: text('description').notNull(),
  price: doublePrecision('price').notNull(),
  prepTimeHours: integer('prep_time_hours').default(1).notNull(),
  stock: integer('stock').notNull(),
  image: text('image').notNull(),
  status: text('status').notNull(),
  unit: text('unit').default('طبق').notNull(),
  prepTimeMinutes: integer('prep_time_minutes').default(45).notNull(),
  rating: doublePrecision('rating').default(5).notNull(),
  reviewCount: integer('review_count').default(0).notNull(),
  createdAt: text('created_at').notNull(),
});

export const orders = pgTable('orders', {
  id: text('id').primaryKey(),
  clientId: text('client_id').notNull(),
  clientName: text('client_name').notNull(),
  clientPhone: text('client_phone').notNull(),
  vendorId: text('vendor_id').notNull(),
  vendorName: text('vendor_name').notNull(),
  vendorAddress: text('vendor_address'),
  vendorLat: doublePrecision('vendor_lat'),
  vendorLng: doublePrecision('vendor_lng'),
  items: jsonb('items').$type<Order['items']>().notNull(),
  subtotalAmount: doublePrecision('subtotal_amount').default(0).notNull(),
  taxRate: doublePrecision('tax_rate'),
  taxAmount: doublePrecision('tax_amount'),
  deliveryFee: doublePrecision('delivery_fee').notNull(),
  commissionRate: doublePrecision('commission_rate'),
  commissionAmount: doublePrecision('commission_amount'),
  grandTotal: doublePrecision('grand_total').notNull(),
  status: text('status').notNull(),
  deliveryAddress: text('delivery_address').notNull(),
  deliveryLocation: jsonb('delivery_location'),
  clientLat: doublePrecision('client_lat'),
  clientLng: doublePrecision('client_lng'),
  distanceKm: doublePrecision('distance_km'),
  estimatedDeliveryMinutes: integer('estimated_delivery_minutes'),
  driverLat: doublePrecision('driver_lat'),
  driverLng: doublePrecision('driver_lng'),
  notes: text('notes'),
  paymentMethod: text('payment_method').default('MADA'),
  couponCode: text('coupon_code'),
  discountAmount: doublePrecision('discount_amount'),
  createdAt: text('created_at').notNull(),
});

export const coupons = pgTable('coupons', {
  id: text('id').primaryKey(),
  code: text('code').notNull(),
  discountPercent: doublePrecision('discount_percent').notNull(),
  maxDiscountAmount: doublePrecision('max_discount_amount'),
  minOrderAmount: doublePrecision('min_order_amount'),
  isActive: boolean('is_active').notNull(),
  usageCount: integer('usage_count').notNull(),
  createdAt: text('created_at').notNull(),
});

export const reviews = pgTable('reviews', {
  id: text('id').primaryKey(),
  productId: text('product_id').notNull(),
  clientName: text('client_name').notNull(),
  rating: doublePrecision('rating').notNull(),
  comment: text('comment').notNull(),
  createdAt: text('created_at').notNull(),
});

export const platformSettingsTable = pgTable('platform_settings', {
  id: text('id').primaryKey(),
  defaultCommissionRate: doublePrecision('default_commission_rate').default(10).notNull(),
  defaultDeliveryFee: doublePrecision('default_delivery_fee').default(15).notNull(),
  freeDeliveryThreshold: doublePrecision('free_delivery_threshold').default(200).notNull(),
  serviceTaxPercent: doublePrecision('service_tax_percent').default(15).notNull(),
  supportPhone: text('support_phone').default('920000000').notNull(),
  allowNewVendorRegistrations: boolean('allow_new_vendor_registrations').default(true).notNull(),
  maintenanceMode: boolean('maintenance_mode').default(false).notNull(),
  announcementBanner: text('announcement_banner').default('').notNull(),
  taxPercentage: doublePrecision('tax_percentage').default(15).notNull(),
  baseDeliveryFeeKm: doublePrecision('base_delivery_fee_km').default(2).notNull(),
});
